#encoding: utf-8
School.create(name: "Noble Street Charter Schools", address: "1 N State St Fl 7TH, Chicago")
School.create(name: "Noble Street Charter -Muchin", address: "1 N State St, Chicago")
School.create(name: "Youth Connections Charter HS", address: "10 W 35th St, Chicago")
School.create(name: "Lyons Twp High Sch", address: "100 S Brainard Ave, La Grange")
School.create(name: "West Leyden High School", address: "1000 N Wolf Rd, Northlake")
School.create(name: "Fenton High School", address: "1000 W Green St, Bensenville")
School.create(name: "Noble Street Charter -Noble", address: "1010 N Noble St, Chicago")
School.create(name: "Glenbard East High School", address: "1014 S Main St, Lombard")
School.create(name: "Julian High School", address: "10330 S Elizabeth St, Chicago")
School.create(name: "Payton College Preparatory HS", address: "1034 N Wells St, Chicago")
School.create(name: "Little Black Pearl Arts Acad HS", address: "1060 E 47th St, Chicago")
School.create(name: "H L Richards High Sch(Campus)", address: "10601 Central Ave, Oak Lawn")
School.create(name: "Chicago International Charter", address: "11 E Adams St Ste 600, Chicago")
School.create(name: "Jefferson Alt High School", address: "1100 S Hamilton Ave, Chicago")
School.create(name: "Maine South High School", address: "1111 S Dee Rd, Park Ridge")
School.create(name: "Fenger Academy High School", address: "11220 S Wallace St, Chicago")
School.create(name: "LEARN Charter Schools", address: "1132 S Homan Ave, Chicago")
School.create(name: "Prologue Early College HS", address: "1135 N Cleaver St, Chicago")
School.create(name: "Clemente Community Academy HS", address: "1147 N Western Ave, Chicago")
School.create(name: "Ralph J Frost Academy", address: "1177 S Dee Rd, Park Ridge")
School.create(name: "Noble Street Charter -Uic", address: "1231 S Damen Ave, Chicago")
School.create(name: "Community Services West High Sch", address: "1239 S Pulaski Rd, Chicago")
School.create(name: "Willowbrook High School", address: "1250 S Ardmore Ave, Villa Park")
School.create(name: "Ogden Int High School", address: "1250 W Erie St, Chicago")
School.create(name: "Chicago Excel Academy HS", address: "1269 W 111th St, Chicago")
School.create(name: "DD Eisenhower High Sch (Campus)", address: "12700 Sacramento Ave, Blue Island")
School.create(name: "Chicago Technology Academy HS", address: "1301 W 14th St, Chicago")
School.create(name: "A B Shepard High Sch (Campus)", address: "13049 S Ridgeland Ave, Palos Heights")
School.create(name: "CICS Charter - Longwood", address: "1309 W 95th St, Chicago")
School.create(name: "Carver Military Academy HS", address: "13100 S Doty Ave, Chicago")
School.create(name: "Univ of Chicago Charter Schools", address: "1313 E 60th St, Chicago")
School.create(name: "Collins Academy High School", address: "1313 S Sacramento Dr, Chicago")
School.create(name: "North Lawndale Charter HS", address: "1313 S Sacramento Dr, Chicago")
School.create(name: "North Lawndale Chtr-Collins", address: "1313 S Sacramento Dr, Chicago")
School.create(name: "Simpson Acad HS for Young Women", address: "1321 S Paulina St, Chicago")
School.create(name: "Urban Prep Chtr Acad West Campus HS", address: "1326 W 14th Pl, Chicago")
School.create(name: "Carl Sandburg High School", address: "13300 S La Grange Rd, Orland Park")
School.create(name: "Noble Street Charter -Rauner", address: "1337 W Ohio St, Chicago")
School.create(name: "IYC Chicago", address: "136 N Western Ave, Chicago")
School.create(name: "Comm H S Dist 99 - South High Sch", address: "1436 Norfolk St, Downers Grove")
School.create(name: "CICS Charter - Chicago Quest North", address: "1443 N Ogden Ave, Chicago")
School.create(name: "Marine Math and Science Academy HS", address: "145 S Campbell Ave, Chicago")
School.create(name: "Phoenix Military Academy HS", address: "145 S Campbell Ave, Chicago")
School.create(name: "Noble Street Charter -Golder", address: "1454 W Superior St, Chicago")
School.create(name: "Oak Forest High School", address: "15201 Central Ave, Oak Forest")
School.create(name: "Bremen High School", address: "15203 Pulaski Rd, Midlothian")
School.create(name: "Prologue - Johnston Fine Arts HS", address: "1549 W 95th St, Chicago")
School.create(name: "Riverside Brookfield Twp HS", address: "160 Ridgewood Rd, Riverside")
School.create(name: "Evanston Twp High School", address: "1600 Dodge Ave, Evanston")
School.create(name: "North Lawndale Chtr-Christiana", address: "1615 S Christiana Ave, Chicago")
School.create(name: "Aspira Charter Schools", address: "1711 N California Ave, Chicago")
School.create(name: "Morgan Park High School", address: "1744 W Pryor Ave, Chicago")
School.create(name: "Maine West High School", address: "1755 S Wolf Rd, Des Plaines")
School.create(name: "J Sterling Morton Freshman Cntr", address: "1801 S 55th Ave, Cicero")
School.create(name: "CICS Charter - Ellison", address: "1817 W 80th St, Chicago")
School.create(name: "J Sterling Morton Alternative Sch", address: "1874 S 54th Ave, Cicero")
School.create(name: "Marine Leadership Academy - Ames", address: "1920 N Hamlin Ave, Chicago")
School.create(name: "Perspectives Charter High School", address: "1930 S Archer Ave, Chicago")
School.create(name: "Perspectives Chtr Joslin", address: "1930 S Archer Ave, Chicago")
School.create(name: "IL Center for Rehab & Educ-R", address: "1950 W Roosevelt Rd, Chicago")
School.create(name: "South Shore Intl Col Prep HS", address: "1955 E 75th St, Chicago")
School.create(name: "Lincoln Park High School", address: "2001 N Orchard St, Chicago")
School.create(name: "Oak Park & River Forest High Sch", address: "201 N Scoville Ave, Oak Park")
School.create(name: "Noble Street Charter -Chgo Bulls", address: "2040 W Adams St, Chicago")
School.create(name: "Chicago Vocational Career Acad HS", address: "2100 E 87th St, Chicago")
School.create(name: "Young Magnet High School", address: "211 S Laflin St, Chicago")
School.create(name: "Back of The Yards IB HS", address: "2111 W 47th St, Chicago")
School.create(name: "Addison Trail High School", address: "213 N Lombard Rd, Addison")
School.create(name: "Prosser Career Academy HS", address: "2148 N Long Ave, Chicago")
School.create(name: "Juarez Community Academy HS", address: "2150 S Laflin St, Chicago")
School.create(name: "Chicago Talent Development HS", address: "2245 W Jackson Blvd, Chicago")
School.create(name: "Crane Medical Prep HS", address: "2245 W Jackson Blvd, Chicago")
School.create(name: "Crane Technical Prep High School", address: "2245 W Jackson Blvd, Chicago")
School.create(name: "Horizon Science Acad-McKinley Park", address: "2245 W Pershing Rd, Chicago")
School.create(name: "Austin Bus & Entrepreneurship HS", address: "231 N Pine Ave, Chicago")
School.create(name: "Austin Polytechnical Academy HS", address: "231 N Pine Ave, Chicago")
School.create(name: "Voise Academy High School", address: "231 N Pine Ave, Chicago")
School.create(name: "Farragut Career Academy HS", address: "2345 S Christiana Ave, Chicago")
School.create(name: "Graham  R Training Center", address: "2347 S Wabash Ave, Chicago")
School.create(name: "J Sterling Morton West High Sch", address: "2400 Home Ave, Berwyn")
School.create(name: "Spry Community Links High School", address: "2400 S Marshall Blvd, Chicago")
School.create(name: "Camelot Safe Academy - Garfield Park", address: "241 N Kolmar, Chicago")
School.create(name: "Ombudsman Chicago West HS", address: "2411 W Congress Pkwy, Chicago")
School.create(name: "J Sterling Morton East High Sch", address: "2423 S Austin Blvd, Cicero")
School.create(name: "Phillips Academy High School", address: "244 E Pershing Rd, Chicago")
School.create(name: "Brooks College Prep Academy HS", address: "250 E 111th St, Chicago")
School.create(name: "Lane Technical High School", address: "2501 W Addison St, Chicago")
School.create(name: "IHSCA Charter High School", address: "2520 S Western Ave, Chicago")
School.create(name: "Instituto Acad Chtr Health Sciences", address: "2520 S Western Ave, Chicago")
School.create(name: "IJLA Charter High School", address: "2570 S Blue Island Ave, Chicago")
School.create(name: "Maine East High School", address: "2601 Dempster St, Park Ridge")
School.create(name: "Young Womens Leadership Chartr HS", address: "2641 S Calumet Ave, Chicago")
School.create(name: "York Alternative High School", address: "2700 S California Ave, Chicago")
School.create(name: "Bowen High School", address: "2710 E 89th St, Chicago")
School.create(name: "Noble Street Charter - Baker Campus", address: "2710 E 89th St, Chicago")
School.create(name: "Chicago HS for the Arts", address: "2714 W Augusta Blvd, Chicago")
School.create(name: "Manley Career Academy High School", address: "2935 W Polk St, Chicago")
School.create(name: "Alcott Humanities High School", address: "2957 N Hoyne Ave, Chicago")
School.create(name: "Aspira - Business & Finance HS", address: "2989 N. Milwaukee Ave., Chicago")
School.create(name: "Dunbar Vocational Career Acad HS", address: "3000 S King Dr, Chicago")
School.create(name: "Steinmetz College Prep HS", address: "3030 N Mobile Ave, Chicago")
School.create(name: "Pathways in Education Avondale HS", address: "3100 W Belmont Ave, Chicago")
School.create(name: "Infinity Math  Science & Tech HS", address: "3120 S Kostner Ave, Chicago")
School.create(name: "Multicultural Acad of Scholarshp HS", address: "3120 S Kostner Ave, Chicago")
School.create(name: "School of Social Justice HS", address: "3120 S Kostner Ave, Chicago")
School.create(name: "World Language High School", address: "3120 S Kostner Ave, Chicago")
School.create(name: "Magic Johnson Academy HS", address: "3222 W Roosevelt Rd, Chicago")
School.create(name: "Westinghouse High School", address: "3223 W Franklin Blvd, Chicago")
School.create(name: "Foreman High School", address: "3235 N Leclaire Ave, Chicago")
School.create(name: "Marshall Metropolitan High School", address: "3250 W Adams St, Chicago")
School.create(name: "Pathways in Education HS", address: "3270 W 87th St, Chicago")
School.create(name: "Devry Advantage Academy High Schl", address: "3300 N Campbell Ave, Chicago")
School.create(name: "Chicago Academy High School", address: "3400 N Austin Ave, Chicago")
School.create(name: "East Leyden High School", address: "3400 Rose St, Franklin Park")
School.create(name: "Roosevelt High School", address: "3436 W Wilson Ave, Chicago")
School.create(name: "Chicago Military Academy HS", address: "3519 S Giles Ave, Chicago")
School.create(name: "Washington G High School", address: "3535 E 114th St, Chicago")
School.create(name: "Raby High School", address: "3545 W Fulton Blvd, Chicago")
School.create(name: "York Comm High School", address: "355 W Saint Charles Rd, Elmhurst")
School.create(name: "Schurz High School", address: "3601 N Milwaukee Ave, Chicago")
School.create(name: "Air Force Acad High School", address: "3630 S Wells St, Chicago")
School.create(name: "Noble Street Charter -Rowe Clark", address: "3645 W Chicago Ave, Chicago")
School.create(name: "Perspectives Chtr iit", address: "3663 S Wabash Ave, Chicago")
School.create(name: "Northside Learning Center", address: "3730 W Bryn Mawr Ave, Chicago")
School.create(name: "Chicago Virtual Charter School", address: "38 S Peoria St, Chicago")
School.create(name: "Chicago HS for Agricult Sciences", address: "3857 W 111th St, Chicago")
School.create(name: "Disney II Magnet HS", address: "3900 N Lawndale Ave, Chicago")
School.create(name: "CICS Charter - Northtown", address: "3900 W Peterson Ave, Chicago")
School.create(name: "Bogan High School", address: "3939 W 79th St, Chicago")
School.create(name: "Delta Learning Center", address: "3940 W Midlothian Tpke, Robbins")
School.create(name: "Aspira Charter - Early College Hs", address: "3986 W Barry Ave, Chicago")
School.create(name: "Lake View High School", address: "4015 N Ashland Ave, Chicago")
School.create(name: "Hancock College Preparatory HS", address: "4034 W 56th St, Chicago")
School.create(name: "Noble Street Charter -Pritzker", address: "4131 W Cortland St, Chicago")
School.create(name: "Kelly High School", address: "4136 S California Ave, Chicago")
School.create(name: "Hinsdale Twp HSD 86 Adult Opportunities Program", address: "42 63rd St, Willowbrook")
School.create(name: "UNO Charter - Major Hector P.Garcia", address: "4248 W 47th St, Chicago")
School.create(name: "Legal Prep Academy Charter HS", address: "4319 W Washington Blvd, Chicago")
School.create(name: "North-Grand High School", address: "4338 W Wabansia Ave, Chicago")
School.create(name: "Kelvyn Park High School", address: "4343 W Wrightwood Ave, Chicago")
School.create(name: "Vaughn Occupational High School", address: "4355 N Linder Ave, Chicago")
School.create(name: "Comm H S Dist 99 - North H S", address: "4436 Main St, Downers Grove")
School.create(name: "King College Prep High School", address: "4445 S Drexel Blvd, Chicago")
School.create(name: "Intrinsic Charter High School", address: "4540 W Belmont Ave, Chicago")
School.create(name: "Proviso West High School", address: "4701 Harrison St, Hillside")
School.create(name: "Tilden Career Communty Academy HS", address: "4747 S Union Ave, Chicago")
School.create(name: "Bronzeville Scholastic HS", address: "4934 S Wabash Ave, Chicago")
School.create(name: "Williams Medical Prep High Sch", address: "4934 S Wabash Ave, Chicago")
School.create(name: "Shabazz Charter -Dusable", address: "4934 S. Wabash, Chicago")
School.create(name: "Peace and Education Coalition HS", address: "4946 S Paulina St, Chicago")
School.create(name: "Curie Metropolitan High School", address: "4959 S Archer Ave, Chicago")
School.create(name: "Richards Career Academy HS", address: "5009 S Laflin St, Chicago")
School.create(name: "Kenwood Academy High School", address: "5015 S Blackstone Ave, Chicago")
School.create(name: "UNO Charter - Soccer Hs", address: "5025 S St. Louis Ave, Chicago")
School.create(name: "Banner West Academy HS", address: "5035 W North Ave, Chicago")
School.create(name: "Von Steuben Metro Science HS", address: "5039 N Kimball Ave, Chicago")
School.create(name: "Clark Acad Prep Magnet High Schl", address: "5101 W Harrison St, Chicago")
School.create(name: "Amundsen High School", address: "5110 N Damen Ave, Chicago")
School.create(name: "Urban Prep Chtr Acad Bronzeville HS", address: "521 E 35th St, Chicago")
School.create(name: "Solorio Academy High School", address: "5400 S St Louis Ave, Chicago")
School.create(name: "Ace Technical Charter High School", address: "5410 S State St, Chicago")
School.create(name: "Douglass Academy High School", address: "543 N Waller Ave, Chicago")
School.create(name: "Hinsdale Central High School", address: "5500 S Grant St, Hinsdale")
School.create(name: "Northside College Preparatory Hs", address: "5501 N Kedzie Ave, Chicago")
School.create(name: "Hope College Prep High School", address: "5515 S Lowe Ave, Chicago")
School.create(name: "Dyett High School", address: "555 E 51st St, Chicago")
School.create(name: "Gage Park High School", address: "5630 S Rockwell St, Chicago")
School.create(name: "Niles West High School", address: "5701 Oakton St, Skokie")
School.create(name: "Mather High School", address: "5835 N Lincoln Ave, Chicago")
School.create(name: "Rickover Naval Academy High Schl", address: "5900 N Glenwood Ave, Chicago")
School.create(name: "Senn High School", address: "5900 N Glenwood Ave, Chicago")
School.create(name: "Reavis High School", address: "6034 W 77th St, Burbank")
School.create(name: "Lindblom Math & Science Acad HS", address: "6130 S Wolcott Ave, Chicago")
School.create(name: "Excel Academy - Woodlawn HS", address: "6145 S Ingleside Ave, Chicago")
School.create(name: "Hubbard High School", address: "6200 S Hamlin Ave, Chicago")
School.create(name: "Team Englewood Comm Acad HS", address: "6201 S Stewart Ave, Chicago")
School.create(name: "Urban Prep Chtr Acad Englewood HS", address: "6201 S Stewart Ave, Chicago")
School.create(name: "Hyde Park Academy High School", address: "6220 S Stony Island Ave, Chicago")
School.create(name: "Kennedy High School", address: "6325 W 56th St, Chicago")
School.create(name: "Noble Street Charter - Johnson", address: "6350 S Stewart Ave, Chicago")
School.create(name: "University of Chicago Charter -Woodlawn", address: "6420 S University Ave, Chicago")
School.create(name: "Harper High School", address: "6520 S Wood St, Chicago")
School.create(name: "Taft High School", address: "6530 W Bryn Mawr Ave, Chicago")
School.create(name: "Sullivan High School", address: "6631 N Bosworth Ave, Chicago")
School.create(name: "Glenbard West High School", address: "670 Crescent Blvd, Glen Ellyn")
School.create(name: "Catalyst Charter - Maria ES", address: "6727 S California Ave, Chicago")
School.create(name: "Amandla Charter School", address: "6800 S Stewart Ave, Chicago")
School.create(name: "Robeson High School", address: "6835 S Normal Blvd, Chicago")
School.create(name: "Jones College Prep High School", address: "700 S State St, Chicago")
School.create(name: "Excel Academy - Southwest HS", address: "7014 S Washtenaw Ave, Chicago")
School.create(name: "Magic Johnson - Roseland HS", address: "7037 S Stony Island Ave, Chicago")
School.create(name: "Noble Street Charter -Comer", address: "7131 S South Chicago Ave, Chicago")
School.create(name: "Excel Academy - Englewood HS", address: "7141 S Morgan St, Chicago")
School.create(name: "Chicago Math & Sci Elem Charter", address: "7212 N Clark St, Chicago")
School.create(name: "Orr Academy High School", address: "730 N Pulaski Rd, Chicago")
School.create(name: "Argo Community High School", address: "7329 W 63rd St, Summit")
School.create(name: "Southside Occupational Acad HS", address: "7342 S Hoyne Ave, Chicago")
School.create(name: "Hinsdale South High School", address: "7401 Clarendon Hills Rd, Darien")
School.create(name: "UNO Charter - Rogers Park (Northside)", address: "7416 N Ridge Ave, Chicago")
School.create(name: "Ombudsman Chicago HS", address: "7500 N Harlem Ave, Chicago")
School.create(name: "Ridgewood Comm High School", address: "7500 W Montrose Ave, Norridge")
School.create(name: "School of Leadership High School", address: "7627 S Constance Ave, Chicago")
School.create(name: "Goode STEM Academy HS", address: "7651 S Homan Ave, Chicago")
School.create(name: "Niles Central", address: "7700 Gross Point Rd, Skokie")
School.create(name: "Hirsch Metropolitan High School", address: "7740 S Ingleside Ave, Chicago")
School.create(name: "Shabazz International Chrtr Schls", address: "7823 S Ellis Ave, Chicago")
School.create(name: "Winnie Mandela High School", address: "7847 S Jeffery Blvd, Chicago")
School.create(name: "Camelot Safe Academy School", address: "7877 S Coles Ave, Chicago")
School.create(name: "CICS Charter - Hawkins", address: "801 E 133rd Pl, Chicago")
School.create(name: "Amos Alonzo Stagg High School", address: "8015 W 111th St, Palos Hills")
School.create(name: "Proviso East High School", address: "807 S 1st Ave, Maywood")
School.create(name: "Perspectives Charter - Leadership Academy", address: "8131 S May St, Chicago")
School.create(name: "Perspectives Chtr Calumet Tech", address: "8131 S May St, Chicago")
School.create(name: "Simeon Career Academy High School", address: "8147 S Vincennes Ave, Chicago")
School.create(name: "Elmwood Park High School", address: "8201 W Fullerton Ave, Elmwood Park")
School.create(name: "Corliss High School", address: "821 E 103rd St, Chicago")
School.create(name: "Noble Street Charter - Pullman Campus (Butler)", address: "821 E 103rd St, Chicago")
School.create(name: "EPIC Academy High School", address: "8255 S Houston Ave, Chicago")
School.create(name: "Proviso Math and Science Academy", address: "8601 Roosevelt Rd, Forest Park")
School.create(name: "Noble Street Charter -Auburn-Gresham Coll (Hansberry)", address: "8748 S Aberdeen St, Chicago")
School.create(name: "Uplift Community High School", address: "900 W Wilson Ave, Chicago")
School.create(name: "Westmont High School", address: "909 Oakwood Dr, Westmont")
School.create(name: "Ford Power House Charter HS", address: "931 S Homan Ave, Chicago")
School.create(name: "Noble Street Charter -Drw Trading College", address: "931 S Homan Ave, Chicago")
School.create(name: "Wells Community Academy HS", address: "936 N Ashland Ave, Chicago")
School.create(name: "Oak Lawn Comm High School", address: "9400 Southwest Hwy, Oak Lawn")
School.create(name: "UNO Academy Charter Schools", address: "954 W Washington Blvd Fl 3, Chicago")
School.create(name: "Harlan Community Academy HS", address: "9652 S Michigan Ave, Chicago")
School.create(name: "Niles North High School", address: "9800 Lawler Ave, Skokie")
School.create(name: "Evergreen Park High School", address: "9901 S Kedzie Ave, Evergreen Park")

Organization.create(name: "Mozilla Foundation", domain_name: "mozillafoundation.org")
Organization.create(name: "Adler Planetarium", domain_name: "adlerplanetarium.org")
Organization.create(name: "After School Matters", domain_name: "afterschoolmatters.org")
Organization.create(name: "After-School All-Stars- Chicago", domain_name: "as-as.org")
Organization.create(name: "BLUE1647 NFP", domain_name: "blue1647.com")
Organization.create(name: "Borderbend Arts Collective", domain_name: "borderbend.org")
Organization.create(name: "Center for College Access and Success", domain_name: "neiu.org")
Organization.create(name: "Center for Community Arts Partnerships", domain_name: "colum.edu")
Organization.create(name: "Center for the Advancement of Science Education", domain_name: "msichicago.org")
Organization.create(name: "Champions Builders Arts Academy Chitown Champions", domain_name: "chitownchampions.com")
Organization.create(name: "Chicago Botanic Garden", domain_name: "chicagobotanic.org")
Organization.create(name: "Chicago History Museum", domain_name: "chicagohistory.org")
Organization.create(name: "Chicago Public Library", domain_name: "chipublib.org")
Organization.create(name: "Chicago Public Schools", domain_name: "cps.edu")
Organization.create(name: "Chicago West Community Music Center", domain_name: "cwcmc.org")
Organization.create(name: "Christopher House", domain_name: "christopherhouse.org")
Organization.create(name: "Ci3's GameChanger Chicago", domain_name: "uchicago.edu")
Organization.create(name: "CICS ChicagoQuest", domain_name: "chicagoquest.org")
Organization.create(name: "City Incite", domain_name: "cityincite.org")
Organization.create(name: "Civic ArtWorks", domain_name: "civicartworks.com")
Organization.create(name: "CoderDojoChi", domain_name: "coderdojochi.org")
Organization.create(name: "College of Education", domain_name: "education.uic.edu")
Organization.create(name: "Columbia Links", domain_name: "columbialinks.org")
Organization.create(name: "Common Sense Education", domain_name: "commonsensemedia.org")
Organization.create(name: "Commonwealth Foundation", domain_name: "commonwlth.org")
Organization.create(name: "Community Film Workshop of Chicago", domain_name: "cfwchicago.org")
Organization.create(name: "Community TV Network", domain_name: "ctvnetwork.org")
Organization.create(name: "Digital Youth Network", domain_name: "digitalyouthnetwork.org")
Organization.create(name: "Donda's House Inc. ", domain_name: "dondashouseinc.org")
Organization.create(name: "For Youth Inquiry", domain_name: "icah.org")
Organization.create(name: "Forall Systems", domain_name: "forallsystems.com")
Organization.create(name: "Free Spirit Media", domain_name: "freespiritmedia.org")
Organization.create(name: "Freedom Games", domain_name: "freedomgames.org")
Organization.create(name: "Gary Comer Youth Center, Inc.", domain_name: "gcychome.org")
Organization.create(name: "Girl Scouts of Greater Chicago and Northwest Indiana", domain_name: "girlscoutsgcnwi.org")
Organization.create(name: "GlobalGirl Media Chicago", domain_name: "globalgirlmedia.org")
Organization.create(name: "Green Star Movement", domain_name: "greenstarmovement.org")
Organization.create(name: "Growing Power Inc.  Chicago Office", domain_name: "growingpower.org")
Organization.create(name: "Growing Power, Inc.", domain_name: "growingpower.org")
Organization.create(name: "Hyde Park Art Center", domain_name: "hydeparkart.org")
Organization.create(name: "Hyde Park Neighborhood Club", domain_name: "hpnclub.org")
Organization.create(name: "IMAN", domain_name: "imancentral.org")
Organization.create(name: "Important Little Games", domain_name: "importantlittlegames.com")
Organization.create(name: "Intuit: The Center for Intuitive and Outsider Art", domain_name: "art.org")
Organization.create(name: "Iridescent", domain_name: "iridescentlearning.org")
Organization.create(name: "John G. Shedd Aquarium", domain_name: "sheddaquarium.org ")
Organization.create(name: "Kuumba Lynx", domain_name: "kuumbalynx.org")
Organization.create(name: "LevelUP IRL", domain_name: "levelupirl.com")
Organization.create(name: "Lincoln Park Zoo", domain_name: "lpzoo.org")
Organization.create(name: "Marwen", domain_name: "marwen.org")
Organization.create(name: "MetaMedia", domain_name: "mcgawymca.org")
Organization.create(name: "Mikva Challenge", domain_name: "mikvachallenge.org")
Organization.create(name: "National Veterans Art Museum", domain_name: "nvam.org")
Organization.create(name: "Open Books LTD", domain_name: "open-books.org")
Organization.create(name: "Peer Health Exchange Chicago", domain_name: "peerhealthexchange.org")
Organization.create(name: "Project Exploration", domain_name: "projectexploration.org")
Organization.create(name: "Project SYNCERE", domain_name: "projectsyncere.org")
Organization.create(name: "Puerto Rican Arts Alliance", domain_name: "praachicago.org")
Organization.create(name: "Red Clay Dance Company", domain_name: "redclaydance.com")
Organization.create(name: "Scenarios USA", domain_name: "scenariosusa.org")
Organization.create(name: "Scientists for Tomorrow", domain_name: "scientistsfortomorrow.org")
Organization.create(name: "Shine On, Chicago!", domain_name: "shineonchicago.com")
Organization.create(name: "Smart Chicago Collaborative", domain_name: "smartchicagocollaborative.org")
Organization.create(name: "Spark Chicago", domain_name: "sparkprogram.org")
Organization.create(name: "Street-Level Youth Media", domain_name: "street-level.org")
Organization.create(name: "Sweet Water Foundation", domain_name: "sweetwaterfoundation.com")
Organization.create(name: "The Anti-Cruelty Society", domain_name: "anticruelty.org")
Organization.create(name: "The ARK of St. Sabina", domain_name: "thearkofstsabina.org")
Organization.create(name: "The Art Institute of Chicago", domain_name: "artic.edu")
Organization.create(name: "The Chicago Academy of Sciences and its Peggy Notebaert Nature Museum", domain_name: "naturemuseum.org")
Organization.create(name: "The Field Museum", domain_name: "fieldmuseum.org")
Organization.create(name: "The News Literacy Project, Chicago", domain_name: "thenewsliteracyproject.org")
Organization.create(name: "The Office of STEM Education Partnerships", domain_name: "northwestern.edu")
Organization.create(name: "The Student Conservation Association", domain_name: "thesca.org")
Organization.create(name: "True Star Media", domain_name: "truestarfoundation.org")
Organization.create(name: "West Town Bikes nfp", domain_name: "westtownbikes.org")
Organization.create(name: "www.NEXT.cc, Inc.", domain_name: "next.cc")
Organization.create(name: "YMCA of Metropolitan Chicago", domain_name: "ymcachicago.org")
Organization.create(name: "Yollocalli Arts Reach", domain_name: "nationalmuseumofmexicanart.org")
Organization.create(name: "Youth Technology Corps NFP, Inc.", domain_name: "youthtechnologycorps.org")
Organization.create(name: "Youtopia", domain_name: "youtopia.com")

Student.create(user_attributes: {email: "example@example.com", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}, nudges_enabled: false, school_id: 1, username: "demo-user")
Student.create(user_attributes: {email: "student@cps.edu", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}, nudges_enabled: true, school_id: 1, username: "cps-student")
Student.create(user_attributes: {email: "rfriedman81@gmail.com", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}, nudges_enabled: true, school_id: 1, username: "omnignorant")

#Admin.create!(user_attributes: {email: "admin@ridewit.me", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}) unless Rails.env.production?
#Admin.create!(user_attributes: {email: "robert@mozillafoundation.org", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}) unless Rails.env.production?
#Admin.create!(user_attributes: {email: "cat@iridescentlearning.org", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}) unless Rails.env.production?

Event.create(name: "Hive Chicago Buzz Hack Day", address: "1647 S. Blue Island Ave.", start_date_and_time: DateTime.iso8601("2016-01-23T11:00:00-06:00"), duration: 1.0, description: "Activate and co-create solutions to transform the learning landscape in Chicago alongside educators and students.", organization_id: 1, minimum_age: 14)

Attendance.create(event: Event.find_by(name: "Hive Chicago Buzz Hack Day"), student: Student.find_by(username: "demo-user"), departure_type: "Late", commitment_status: "Yes", method_of_transit: "walking")
Attendance.create(event: Event.find_by(name: "Hive Chicago Buzz Hack Day"), student: Student.find_by(username: "cps-student"), departure_type: "Late", commitment_status: "Yes", method_of_transit: "walking")
Attendance.create(event: Event.find_by(name: "Hive Chicago Buzz Hack Day"), student: Student.find_by(username: "omnignorant"), departure_type: "Late", commitment_status: "Yes", method_of_transit: "walking")
