#encoding: utf-8
School.create(name: "ALPHA OMEGA MINISTRIES", address: "1251 N PARKSIDE AVE")
School.create(name: "AUSTIN CAREER EDUCATION CENTER", address: "5352 W CHICAGO AVE")
School.create(name: "Acad of Comm & Technology", address: "4319 W Washington Bl")
School.create(name: "Ace Tech Charter", address: "5410 S State St")
School.create(name: "Advantage Acad-Devry", address: "3300 N Campbell Ave")
School.create(name: "Amundsen HS", address: "5110 N Damen Av")
School.create(name: "Antonia Pantoja High School", address: "3121 N Pulaski Rd")
School.create(name: "Austin HS", address: "231 N Pine Av")
School.create(name: "BEST Academy", address: "2710 E 89th St")
School.create(name: "BROWN CAMPUS", address: "1460 W SUPERIOR ST")
School.create(name: "Bais Yaakov HS", address: "3333 W Peterson Av")
School.create(name: "Banner Academy West", address: "5035 W North Ave")
School.create(name: "Best Practice", address: "2042 W Adams St")
School.create(name: "Best Practices HS", address: "2040 W Adams St")
School.create(name: "Big Picture HS", address: "2710 S Dearborn St")
School.create(name: "Big Picture at Chavez", address: "4946 S Paulina St")
School.create(name: "Bogan Tech HS", address: "3939 W 79th St")
School.create(name: "Bowen", address: "2710 E 89th St")
School.create(name: "Brisk Academy-Yeshivas Brisk", address: "3000 W. Devon Avenue")
School.create(name: "Brooks College Prep", address: "250 E 111th St")
School.create(name: "Brother Rice HS", address: "10001 S Pulaski Rd")
School.create(name: "CHGO. INT. CHARTER - RALPH ELLISON", address: "1547 W 95TH ST")
School.create(name: "COMM YOUTH DEVELOPMENT INSTITUTE", address: "7832 S UNION AVE")
School.create(name: "CONSUELLA B. YORK ALTERNATIVE HS", address: "2700 S CALIFORNIA AVE")
School.create(name: "Calumet HS", address: "8131 S May St")
School.create(name: "Carver HS", address: "13100 S Carver Dr")
School.create(name: "Chicago Acad For The Arts", address: "1010 W Chicago")
School.create(name: "Chicago Agricultural HS", address: "3807 W 111th St")
School.create(name: "Chicago Discovery", address: "2710 E 89th St")
School.create(name: "Chicago Hope Academy", address: "2189 W Bowler St")
School.create(name: "Chicago International Northtown", address: "3900 W Peterson Av")
School.create(name: "Chicago Military Acad", address: "3519 S Giles Av")
School.create(name: "Chicago Vocational HS", address: "2100 E 87th St")
School.create(name: "Clark Middle", address: "5101 W Harrison St")
School.create(name: "Clemente Community HS", address: "1147 N Western Av")
School.create(name: "Collins HS", address: "1313 S Sacramento Dr")
School.create(name: "Comm Christian Alt Acad", address: "1231 S Pulaski Rd")
School.create(name: "Corliss HS", address: "821 E 103rd St")
School.create(name: "Cosmopolitan Preparatory", address: "188 W. Randolph")
School.create(name: "Crane Tech HS", address: "2245 W Jackson Bl")
School.create(name: "Cregier Multiplex", address: "2040 W Adams St")
School.create(name: "Cristo Rey Jesuit High School", address: "1851 W Cermak Road")
School.create(name: "Curie HS", address: "4959 S Archer Av")
School.create(name: "Dr Pedro Albizu Campos Hs", address: "1671 N Claremont")
School.create(name: "DuSable HS", address: "4934 S Wabash Av")
School.create(name: "Dunbar Vocational HS", address: "3000 S Dr Martin Luther King Jr Dr")
School.create(name: "Dyett Middle", address: "555 E 51st St")
School.create(name: "Englewood HS", address: "6201 S Stewart Av")
School.create(name: "Farragut HS", address: "2345 S Christiana Av")
School.create(name: "Fenger HS", address: "11220 S Wallace St")
School.create(name: "Foreman HS", address: "3235 N Leclaire Av")
School.create(name: "Gage Park HS", address: "5630 S Rockwell St")
School.create(name: "Garfield Alternative High Scho", address: "220 West 45th Place")
School.create(name: "Gordon Tech HS", address: "3633 N California Av")
School.create(name: "HACC", address: "7647 N PAULINA AVE")
School.create(name: "HUNTER-BOLDEN ACADEMY?", address: "512 N MCCLURG CT")
School.create(name: "Hales Franciscan HS", address: "4930 S Cottage Grove Av")
School.create(name: "Hancock", address: "4034 W 56th St")
School.create(name: "Hanna Sacks Bais", address: "3021 W Devon Av")
School.create(name: "Harlan HS", address: "9652 S Michigan Av")
School.create(name: "Harper HS", address: "6520 S Wood St")
School.create(name: "Hirsch Metro HS", address: "7740 S Ingleside Av")
School.create(name: "Holy Trinity HS", address: "1443 W Division St")
School.create(name: "Hope College Prep", address: "5515 S Lowe Av")
School.create(name: "Hubbard HS", address: "6200 S Hamlin Av")
School.create(name: "Hunter-Bolden Academy", address: "5946 S Prairie Ave")
School.create(name: "Hyde Park H S", address: "6220 S Stony Island Av")
School.create(name: "IDOC/HEALY BR - N JEFFERSON ALT SCH", address: "100 N WESTERN AVE")
School.create(name: "IDOC/HEALY SOUTH", address: "8007 S COTTAGE GROVE AVE")
School.create(name: "INFINITY HS", address: "3120 S KOSTNER AV")
School.create(name: "Ida Crown Academy", address: "2828 W Pratt Blvd")
School.create(name: "JANE ADDAMS RESOURCE CORP", address: "1800 W CUYLER AVE")
School.create(name: "Jane Addams High School", address: "1814 S UNION AVE")
School.create(name: "Jones HS", address: "606 S State St")
School.create(name: "Josephinum HS", address: "1501 N Oakley Bl")
School.create(name: "Juarez H S", address: "2150 S Laflin St")
School.create(name: "Julian HS", address: "10330 S Elizabeth St")
School.create(name: "Kelly HS", address: "4136 S California Av")
School.create(name: "Kelvyn Park HS", address: "4343 W Wrightwood Av")
School.create(name: "Kennedy HS", address: "6325 W 56th St")
School.create(name: "Kenwood Acad HS", address: "5015 S Blackstone Av")
School.create(name: "King HS", address: "4445 S Drexel Bl")
School.create(name: "LINC ALT HIGH SCHOOL", address: "5035 W NORTH AVE")
School.create(name: "LITTLE VILLAGE CAMPUS", address: "3120 S KOSTNER AV")
School.create(name: "LYDIA URBAN ACADEMY", address: "4300 W IRVING PARK RD")
School.create(name: "Lake View Acad", address: "716 W Addison St")
School.create(name: "Lake View HS", address: "4015 N Ashland Av")
School.create(name: "Lane Tech HS", address: "2501 W Addison St")
School.create(name: "Latino Youth High School", address: "2001 S CALIFORNIA AVE")
School.create(name: "Leo HS", address: "7901 S Sangamon St")
School.create(name: "Lincoln Park HS", address: "2001 N Orchard St")
School.create(name: "Lindblom Tech HS", address: "6130 S Wolcott Av")
School.create(name: "Lubavitch Boy's High School", address: "2756 W Morse Avenue")
School.create(name: "Lubavitch Girls HS", address: "6350 N Whipple St")
School.create(name: "Luther HS North", address: "5700 W Berteau Av")
School.create(name: "MARIN PREPARATORY SCHOOL?", address: "240 W RANDOLPH ST")
School.create(name: "MAROON CAMPUS", address: "3645 W CHICAGO AVE")
School.create(name: "MULTI-CULTURAL ARTS", address: "3120 S KOSTNER AV")
School.create(name: "Manley HS", address: "2935 W Polk St")
School.create(name: "Maria HS", address: "6727 S California Av")
School.create(name: "Marist HS", address: "4200 W 115th St")
School.create(name: "Marshall Metro HS", address: "3250 W Adams St")
School.create(name: "Mather HS", address: "5835 N Lincoln Av")
School.create(name: "Morgan Park HS", address: "1744 W Pryor Av")
School.create(name: "Moses Vines", address: "730 N Pulaski Rd")
School.create(name: "Mother McAuley HS", address: "3737 W 99th St")
School.create(name: "Mount Carmel HS", address: "6410 S Dante Av")
School.create(name: "NANCY B JEFFERSON ALT SCHOOL", address: "1100 S HAMILTON AVE")
School.create(name: "NOBLE - ESCALANTE COLLEGE PREP", address: "1460 W SUPERIOR ST")
School.create(name: "NOBLE - ROWE-CLARK MATH & SCI ACAD", address: "3645 W CHICAGO AVE")
School.create(name: "New Birth Training Institute", address: "5510 W Chicago Ave")
School.create(name: "Noble Street Charter", address: "1400 W Augusta Bl")
School.create(name: "North Lawndale Charter", address: "1616 N Spaulding Av")
School.create(name: "North-Grand", address: "4338 W Wabansia Ave")
School.create(name: "Northside College Prep", address: "5501 N Kedzie Av")
School.create(name: "Notre Dame HS", address: "3000 N Mango Av")
School.create(name: "Orr HS", address: "730 N Pulaski Rd")
School.create(name: "Our Lady of Tepeyac HS", address: "2228 S Whipple St")
School.create(name: "PEACE AND EDUCATION COALITION HS", address: "4541 S WOOD ST")
School.create(name: "PROLOGUE EARLY COLLEGE", address: "640 W IRVING PARK RD")
School.create(name: "PUERTO RICAN H S - PEDRO A CAMPOS", address: "2739 W DIVISION ST")
School.create(name: "Perspectives Charter", address: "1915 S Federal St")
School.create(name: "Phillips Acad", address: "244 E Pershing Rd")
School.create(name: "Phoenix Military Academy", address: "730 N Pulaski Rd")
School.create(name: "Prosser Vocational HS", address: "2148 N Long Av")
School.create(name: "Ramirez Computer Science", address: "2431 N Western Av")
School.create(name: "Resurrection HS", address: "7500 W Talcott Av")
School.create(name: "Richards HS", address: "5009 S Laflin St")
School.create(name: "Robeson", address: "6835 S Normal Blvd")
School.create(name: "Roosevelt HS", address: "3436 W Wilson Av")
School.create(name: "SECOND CHANCE ALTERNATIVE HS", address: "5114 S ELIZABETH ST")
School.create(name: "School Of Entrepeneurship", address: "7627 S Constance Ave")
School.create(name: "School of Leadership", address: "7627 S Constance Ave")
School.create(name: "School of Leadership", address: "7627 S Constance Ave")
School.create(name: "School of the Arts", address: "7529 S Constance Av")
School.create(name: "Schurz HS", address: "3601 N Milwaukee Av")
School.create(name: "Senn Metro Acad", address: "5900 N Glenwood Av")
School.create(name: "Simeon", address: "8235 S Vincennes Av")
School.create(name: "South Shore HS", address: "7529 S Constance Av")
School.create(name: "St Barbara High School", address: "2867 S Throop St")
School.create(name: "St Benedict", address: "3920 N Leavitt St")
School.create(name: "St Benedicts HS", address: "3900 N Leavitt St")
School.create(name: "St Francis de Sales HS", address: "10155 S Ewing Av")
School.create(name: "St Gregory High School", address: "1677 W Bryn Mawr Ave")
School.create(name: "St Ignatius Prep HS", address: "1076 W Roosevelt Rd")
School.create(name: "St Patrick HS", address: "5900 W Belmont Av")
School.create(name: "St Rita HS", address: "7740 S Western Av")
School.create(name: "St Scholastica HS", address: "7416 N Ridge Bl")
School.create(name: "Steinmetz HS", address: "3030 N Mobile Av")
School.create(name: "Sullivan HS", address: "6631 N Bosworth Av")
School.create(name: "Sullivan House", address: "8164 S South Chicago Avenue")
School.create(name: "Taft HS", address: "6545 W Hurlbut St")
School.create(name: "Telshe High School", address: "3535 W Foster Avenue")
School.create(name: "Tilden HS", address: "4747 S Union Av")
School.create(name: "VIVIAN E SUMMERS ALTERNATIVE HS", address: "30 E 112TH PL")
School.create(name: "Von Steuben HS", address: "5039 N KIMBALL AVE")
School.create(name: "WORLD LANGUAGE HS", address: "3120 S KOSTNER AV")
School.create(name: "Walter Payton", address: "1034 N Wells St")
School.create(name: "Washington HS", address: "3535 E 114th St")
School.create(name: "Wells HS", address: "936 N Ashland Av")
School.create(name: "Westinghouse HS", address: "3301 W Franklin Bl")
School.create(name: "Westown Acad", address: "2021 W Fulton St")
School.create(name: "Westside Alternative High School", address: "4909 W DIVISION ST")
School.create(name: "Whitney Young HS", address: "211 S Laflin St")
School.create(name: "Youth Connections Charter School", address: "10 W 35th St")
Organization.create(name: "Adler Planetarium", domain_name: "adlerplanetarium.org")
Organization.create(name: "After School Matters", domain_name: "afterschoolmatters.org")
Organization.create(name: "After-School All-Stars- Chicago", domain_name: "as-as.org")
Organization.create(name: "BLUE1647 NFP", domain_name: "blue1647.com")
Organization.create(name: "Borderbend Arts Collective", domain_name: "borderbend.org")
Organization.create(name: "Center for College Access and Success", domain_name: "neiu.org")
Organization.create(name: "Center for Community Arts Partnerships", domain_name: "colum.edu")
Organization.create(name: "Center for the Advancement of Science Education", domain_name: "msichicago.org")
Organization.create(name: "Champions Builders Arts Academy Chitown Champions", domain_name: "chitownchampions.com")
Organization.create(name: "Chicago Botanic Garden", domain_name: "chicagobotanic.org")
Organization.create(name: "Chicago History Museum", domain_name: "chicagohistory.org")
Organization.create(name: "Chicago Public Library", domain_name: "chipublib.org")
Organization.create(name: "Chicago Public Schools", domain_name: "cps.edu")
Organization.create(name: "Chicago West Community Music Center", domain_name: "cwcmc.org")
Organization.create(name: "Christopher House", domain_name: "christopherhouse.org")
Organization.create(name: "Ci3's GameChanger Chicago", domain_name: "uchicago.edu")
Organization.create(name: "CICS ChicagoQuest", domain_name: "chicagoquest.org")
Organization.create(name: "City Incite", domain_name: "cityincite.org")
Organization.create(name: "Civic ArtWorks", domain_name: "civicartworks.com")
Organization.create(name: "CoderDojoChi", domain_name: "coderdojochi.org")
Organization.create(name: "College of Education", domain_name: "education.uic.edu")
Organization.create(name: "Columbia Links", domain_name: "columbialinks.org")
Organization.create(name: "Common Sense Education", domain_name: "commonsensemedia.org")
Organization.create(name: "Commonwealth Foundation", domain_name: "commonwlth.org")
Organization.create(name: "Community Film Workshop of Chicago", domain_name: "cfwchicago.org")
Organization.create(name: "Community TV Network", domain_name: "ctvnetwork.org")
Organization.create(name: "Digital Youth Network", domain_name: "digitalyouthnetwork.org")
Organization.create(name: "Donda's House Inc. ", domain_name: "dondashouseinc.org")
Organization.create(name: "For Youth Inquiry", domain_name: "icah.org")
Organization.create(name: "Forall Systems", domain_name: "forallsystems.com")
Organization.create(name: "Free Spirit Media", domain_name: "freespiritmedia.org")
Organization.create(name: "Freedom Games", domain_name: "freedomgames.org")
Organization.create(name: "Gary Comer Youth Center, Inc.", domain_name: "gcychome.org")
Organization.create(name: "Girl Scouts of Greater Chicago and Northwest Indiana", domain_name: "girlscoutsgcnwi.org")
Organization.create(name: "GlobalGirl Media Chicago", domain_name: "globalgirlmedia.org")
Organization.create(name: "Green Star Movement", domain_name: "greenstarmovement.org")
Organization.create(name: "Growing Power Inc.  Chicago Office", domain_name: "growingpower.org")
Organization.create(name: "Growing Power, Inc.", domain_name: "growingpower.org")
Organization.create(name: "Hyde Park Art Center", domain_name: "hydeparkart.org")
Organization.create(name: "Hyde Park Neighborhood Club", domain_name: "hpnclub.org")
Organization.create(name: "IMAN", domain_name: "imancentral.org")
Organization.create(name: "Important Little Games", domain_name: "importantlittlegames.com")
Organization.create(name: "Intuit: The Center for Intuitive and Outsider Art", domain_name: "art.org")
Organization.create(name: "Iridescent", domain_name: "iridescentlearning.org")
Organization.create(name: "John G. Shedd Aquarium", domain_name: "sheddaquarium.org ")
Organization.create(name: "Kuumba Lynx", domain_name: "kuumbalynx.org")
Organization.create(name: "LevelUP IRL", domain_name: "levelupirl.com")
Organization.create(name: "Lincoln Park Zoo", domain_name: "lpzoo.org")
Organization.create(name: "Marwen", domain_name: "marwen.org")
Organization.create(name: "MetaMedia", domain_name: "mcgawymca.org")
Organization.create(name: "Mikva Challenge", domain_name: "mikvachallenge.org")
Organization.create(name: "Mozilla Foundation", domain_name: "mozillafoundation.org")
Organization.create(name: "National Veterans Art Museum", domain_name: "nvam.org")
Organization.create(name: "Open Books LTD", domain_name: "open-books.org")
Organization.create(name: "Peer Health Exchange Chicago", domain_name: "peerhealthexchange.org")
Organization.create(name: "Project Exploration", domain_name: "projectexploration.org")
Organization.create(name: "Project SYNCERE", domain_name: "projectsyncere.org")
Organization.create(name: "Puerto Rican Arts Alliance", domain_name: "praachicago.org")
Organization.create(name: "Red Clay Dance Company", domain_name: "redclaydance.com")
Organization.create(name: "Scenarios USA", domain_name: "scenariosusa.org")
Organization.create(name: "Scientists for Tomorrow", domain_name: "scientistsfortomorrow.org")
Organization.create(name: "Shine On, Chicago!", domain_name: "shineonchicago.com")
Organization.create(name: "Smart Chicago Collaborative", domain_name: "smartchicagocollaborative.org")
Organization.create(name: "Spark Chicago", domain_name: "sparkprogram.org")
Organization.create(name: "Street-Level Youth Media", domain_name: "street-level.org")
Organization.create(name: "Sweet Water Foundation", domain_name: "sweetwaterfoundation.com")
Organization.create(name: "The Anti-Cruelty Society", domain_name: "anticruelty.org")
Organization.create(name: "The ARK of St. Sabina", domain_name: "thearkofstsabina.org")
Organization.create(name: "The Art Institute of Chicago", domain_name: "artic.edu")
Organization.create(name: "The Chicago Academy of Sciences and its Peggy Notebaert Nature Museum", domain_name: "naturemuseum.org")
Organization.create(name: "The Field Museum", domain_name: "fieldmuseum.org")
Organization.create(name: "The News Literacy Project, Chicago", domain_name: "thenewsliteracyproject.org")
Organization.create(name: "The Office of STEM Education Partnerships", domain_name: "northwestern.edu")
Organization.create(name: "The Student Conservation Association", domain_name: "thesca.org")
Organization.create(name: "True Star Media", domain_name: "truestarfoundation.org")
Organization.create(name: "West Town Bikes nfp", domain_name: "westtownbikes.org")
Organization.create(name: "www.NEXT.cc, Inc.", domain_name: "next.cc")
Organization.create(name: "YMCA of Metropolitan Chicago", domain_name: "ymcachicago.org")
Organization.create(name: "Yollocalli Arts Reach", domain_name: "nationalmuseumofmexicanart.org")
Organization.create(name: "Youth Technology Corps NFP, Inc.", domain_name: "youthtechnologycorps.org")
Organization.create(name: "Youtopia", domain_name: "youtopia.com")

Student.create(user_attributes: {email: "example@example.com", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}, nudges_enabled: false, school_id: 1, username: "demo-user")
Student.create(user_attributes: {email: "student@cps.edu", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}, nudges_enabled: true, school_id: 1, username: "cps-student")
Student.create(user_attributes: {email: "rfriedman81@gmail.com", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}, nudges_enabled: true, school_id: 1, username: "omnignorant")

unless Rails.env.production?
  Admin.create!(user_attributes: {email: "admin@ridewit.me", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}) unless Rails.env.production?
  Admin.create!(user_attributes: {email: "robert@mozillafoundation.org", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}) unless Rails.env.production?
  Admin.create!(user_attributes: {email: "cat@iridescentlearning.org", password: "password1234", phone: "+11111111111", phone_verified: true, email_verified: true}) unless Rails.env.production?
end

Event.create(name: "Hive Chicago Buzz Hack Day", address: "1647 S Blue Island Ave", start_date_and_time: DateTime.iso8601("2016-01-23T11:00:00-08:00"), duration: 8.0, description: "Active and co-create solutions to transform the learning landscape of Chicago", organization_id: 1)

Attendance.create(event: Event.find_by(name: "Chicago Southside Mini Maker Faire"), student: Student.find_by(username: "jsub"), departure_type: "On Time", commitment_status: "Yes", method_of_transit: "transit")
